"""
Stage 17: Automatic BibTeX Fixing.
Generates a cleaned, corrected, and formatted BibTeX file.
"""
from __future__ import annotations

from ..models.report import EntryReport


def run_stage_17(entry_reports: list[EntryReport]) -> str:
    """Combine corrected BibTeX entries into a complete .bib file string."""
    bib_blocks = []
    for r in entry_reports:
        if r.corrected_bib:
            bib_blocks.append(r.corrected_bib.strip())

    header = "% Automatically corrected BibTeX generated by SCVA (Scientific Citation Verification Agent)\n\n"
    return header + "\n\n".join(bib_blocks) + "\n"
